### ISSUE TITLE
Support arrays of hierarchical settings

### ISSUE THREAD

**Issue by oxc** [markt-de/puppet-nextcloud#1]
The `$config` system supports setting Arrays and Structs (php associative arrays), but for some config keys, an Array of Structs is required. 

The most prominent example is perhaps `apps_paths`:

```php
'apps_paths' => [
        [
                'path'=> '/var/www/nextcloud/apps',
                'url' => '/apps',
                'writable' => true,
        ],
],
```

I expected to be able to use this from hiera yaml as:

```yaml
nextcloud::config:
  app_paths:
    - path: /opt/nextcloud/apps
      url: /apps
      writable: false
    - path: /opt/nextcloud-user-apps/
      url: /user-apps/
      writable: true
```

This fails with:
> parameter 'value' expects a value of type Boolean, Integer, or String, got Struct
> parameter 'verify_value' expects a value of type Boolean, Integer, or String, got Struct

Currently, this can be worked around by putting the array indices into the key names:

```yaml
nextcloud::config:
  app_paths 0:
      path: /opt/nextcloud/apps
      url: /apps
      writable: false
  app_paths 1:
      path: /opt/nextcloud-user-apps/
      url: /user-apps/
      writable: true
```

Perhaps the code from `nextcloud::config` can be extracted into a recursive function to properly support this?
